# Generated by Django 3.2 on 2021-08-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucclms', '0003_auto_20210802_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='date_of_issue',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='date_of_return',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='due_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
