# Generated by Django 3.2 on 2021-08-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucclms', '0004_auto_20210802_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='date_of_issue',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='date_of_return',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
