# Generated by Django 3.2 on 2021-08-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucclms', '0006_alter_recommendation_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
