# Generated by Django 3.2.3 on 2021-10-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucclms', '0017_alter_bookrecord_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
