# Generated by Django 3.2.3 on 2021-10-20 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucclms', '0018_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='Subject',
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booksubject', to='ucclms.subject'),
        ),
    ]
