# Generated by Django 3.2.3 on 2021-10-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucclms', '0019_auto_20211021_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_stolen',
            field=models.BooleanField(default=False),
        ),
    ]
