# Generated by Django 3.2.6 on 2021-10-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucclms', '0020_book_is_stolen'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='no_stolen',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
